development:
  adapter: postgresql
  encoding: unicode
  database: words_development
  pool: 5
  host: localhost
  username: nickyhughes
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: words_test
  pool: 5
  host: localhost
  username: nickyhughes
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: words_production
  pool: 5
  host: localhost
  username: nickyhughes
  password:
